Cargo.toml, README.md
Using `/` is considered deprecated and using `OR` is preferred.
=> Use valid SPDX 2.1 license expression.

.github/workflows/ci.yml
This isn't maintained any longer, so just run `cargo` directly as in the other job steps.
=> ci: Don't use `actions-rs/cargo`.

demo/src/main.rs
Due to this [error/related issue](https://github.com/bevyengine/bevy/issues/10157#issuecomment-1799066736) on wasm builds with the new bevy assetv2 pipeline, the recommended solution was to disable asset meta data checks.
=> Remove bevy asset meta data check

README.md, demo/src/main.rs, src/lib.rs, src/renderer/extract.rs, src/renderer/prepare.rs, src/renderer/render.rs, src/rendertarget.rs
- Added a `RenderMode` struct to define `RenderMode::ScreenSpace` or `RenderMode::WorldSpace` . 
- Removed the `Layer` struct which previously defined the draw order.
Redid the render ordering to sort by the vector's **z** position since the transform is already being included for a 2d affine transformation so the **z** component doesn't go unused; this is assuming the z component of the transform isn't used to represent other things. Vectors in world-space are rendered first, then screen-space so that screen-space vectors have their own independent z-ordering.
Previously text was already rendered after other vectors so it would always appear on top, I changed this behavior to follow along with the ordering of all the other vectors, regardless if it's text or not.
=> Redid render ordering

.github/workflows/release.yml, CHANGELOG.md, Cargo.toml, README.md, demo/Cargo.toml, examples/drag-n-drop/Cargo.toml, examples/text/Cargo.toml, examples/text/src/main.rs, examples/z-ordering/Cargo.toml, shaders/vello_ss_rendertarget.wgsl, src/assets/asset.rs, src/assets/parser.rs, src/player/systems.rs, src/render/extract.rs, src/render/mod.rs, src/render/plugin.rs, src/render/systems.rs, src/text/font.rs
Addresses #34 
Updating to bevy 0.13 requires updating vello to match wgpu versions with bevy. Updating vello comes with some challenges. SceneBuilder no longer exists. SceneFragment as well. vellottie and vello-svg likewise will need vello updates.
Also, bevy changed the ExtractComponent trait to where it didn't make sense for our uses in the VelloFont extract step, so it's being removed in favor of an extraction system like that used to make ExtractedRenderVector. So fonts should be regression tested. Vello no longer uses fello, instead reimports skifra-- all the font rendering abstraction on top of vello will need changed to support this, so lets pay close attention to fonts/text.
=> WIP: Bevy 0.13 updates

CHANGELOG.md, Cargo.toml, src/render/plugin.rs, src/render/systems.rs
The motivation for this began as a way to work around [this bevy issue](https://github.com/bevyengine/bevy/issues/12912), which it does successfully circumvent. But also this makes `render_scene` make proper use of `Local`, so this is also an general improvement.
=> Make render system use `Local` for Vello Renderer

CHANGELOG.md, Cargo.toml, examples/scene-ui/Cargo.toml, examples/scene-ui/src/main.rs, src/render/extract.rs, src/render/prepare.rs
This PR fixes a couple issues I had when trying to use a `VelloScene` with Bevy's UI:
1. The Y-axis was flipped, so that setting any `top` or `bottom` value on the `Style` component caused the `VelloScene` to move in the opposite direction from the node
2. Bevy's layout system puts the transform origin at the center of the node's computed bounding box, which is awkward for a canvas-like API where you expect to be issuing draw commands with the origin at the bounding box corner.
That said, I know there are different conventions for whether the Y-origin is top or bottom, and I'm honestly not sure where Vello's origin is under normal circumstances. Let me know if you'd like to preserve a bottom-left origin for Vello drawing commands while still positioning the Vello scene so that it aligns …
=> Fix render matrix for `VelloScene`s in Bevy UI nodes

.cargo/config.toml, CHANGELOG.md, Cargo.toml, examples/demo/Cargo.toml, examples/demo/src/main.rs, src/render/systems.rs
- Updated to patch vello 0.2.1. It is now no-longer possible to panic when the vello encodings are empty.
- The demo CI now deploys that bevy_pancam has been updated to bevy 0.14
=> v0.5.1 - Release

CHANGELOG.md, examples/demo/src/main.rs, examples/demo/src/ui.rs, examples/drag_n_drop/Cargo.toml, examples/drag_n_drop/src/main.rs, examples/lottie/src/main.rs, examples/svg/src/main.rs, examples/text/src/main.rs, src/debug.rs, src/integrations/asset.rs, src/integrations/lottie/asset_loader.rs, src/integrations/lottie/parse.rs, src/integrations/mod.rs, src/integrations/svg/asset_loader.rs, src/integrations/svg/parse.rs, src/lib.rs, src/render/extract.rs, src/render/prepare.rs, src/render/systems.rs, src/text/font.rs, src/text/mod.rs, src/text/vello_text.rs
Renames `Alignment`s to `Anchor`s. This is consistent with how bevy names the equivalent component, `Anchor` within `Text2dBundle`. (https://docs.rs/bevy/latest/bevy/text/struct.Text2dBundle.html).
Also, this corrects and consistently names fields in the internals, not in the public API.
=> refactor: naming to be consistent

CHANGELOG.md, Cargo.toml, examples/cube3d/Cargo.toml, examples/cube3d/src/main.rs, examples/render_layers/Cargo.toml, examples/render_layers/src/main.rs, examples/text/Cargo.toml, examples/text/src/main.rs, src/render/extract.rs, src/render/mod.rs, src/render/plugin.rs, src/render/prepare.rs, src/render/systems.rs
This is a rebased version of #49 which looks like it only needed merge conflicts resolved
=> Fix render layers

CHANGELOG.md, examples/cube3d/src/main.rs, examples/demo/src/main.rs, examples/drag_n_drop/src/main.rs, examples/lottie/src/main.rs, examples/render_layers/src/main.rs, examples/scene/src/main.rs, examples/scene_ui/src/main.rs, examples/svg/src/main.rs, examples/text/src/main.rs, src/lib.rs, src/plugin.rs, src/render/mod.rs, src/render/plugin.rs, src/render/systems.rs
This is the fix I talked about in #70 and the PR that would be merged (the other should be closed)
This PR adds a config option to `VelloPlugin` and `VelloRenderPlugin` that can control the `RenderLayers` that the `VelloCanvas` is on. This allows fully taking advantage of `RenderLayers` as before the canvas was rendering on the default layer, layer 0, which meant any camera that wanted to render it also had to render everything else on the default layer, layer 0.
=> Pass RenderLayers to VelloCanvas

CHANGELOG.md, examples/scene/src/main.rs, src/lib.rs, src/render/extract.rs, src/render/mod.rs
Adds the `SkipEncoding` component which allows us to skip rendering any renderable entity
=> feat: add `SkipEncoding`

CHANGELOG.md
Needs to be delivered ahead of #75 
See discussion there.
=> docs: improve changelog

CHANGELOG.md, Cargo.toml, README.md
=> [RELEASE] chore: update to 0.6.0

CHANGELOG.md, Cargo.toml, src/render/extract.rs
Text is now properly skipped when a `SkipEncoding` component is present.
=> fix: skip text when `SkipEncoding` is present

.cargo/config.toml, Cargo.lock, Cargo.toml
We no longer need to pin getrandom's backend due to a transitive dependency in uuid. This was fixed today by https://github.com/bevyengine/bevy/issues/17699#issuecomment-2641490699
=> fix: no longer need to pin uuid and getrandom

CHANGELOG.md, examples/demo/src/main.rs, examples/drag_n_drop/src/main.rs, examples/lottie/src/main.rs, examples/render_layers/src/main.rs, examples/scene/src/main.rs, examples/scene_ui/src/main.rs, examples/svg/src/main.rs, examples/text/src/main.rs, src/debug.rs, src/integrations/dot_lottie/systems.rs, src/lib.rs, src/render/mod.rs, src/render/plugin.rs, src/render/prepare.rs, src/render/systems.rs
It is common for Bevy cameras to mark what graphics features they use using a marker component, such as bloom or SSR, to name a few built-in effects that do this. In my game, I have cameras that don't need any Vello content at all. If I've read the logic correctly, they still pay the tax of running Vello code.
bevy_vello's `render_frame` system is currently the most demanding system in my game, and this PR seems to push it down to second place, although it is quite difficult to measure precisely.
Note that this is a breaking change, since users now have to add the `VelloView` component to their camera or nothing will render.
=> Require a VelloView marker for cameras rendering Vello graphics

.github/workflows/ci.yml, Cargo.lock, examples/cube3d/Cargo.toml
The cube3d example recently broke due to bevy_vello removing PBR, but it is needed specifically for this example.
=> fix: add bevy_pbr to cube3d example

.github/workflows/ci.yml, Cargo.lock, examples/drag_n_drop/Cargo.toml, examples/drag_n_drop/src/main.rs
Enhances the drag_n_drop demo to be more wasm friendly, namely adding a button which allows you to select a file to open and preview a Lottie or SVG file, since dragging a file into the web browser did not work as intended.
=> feat: web compatible drag_n_drop demo

.github/workflows/web-demo.yml, .github/workflows/web-release.yml, README.md
=> ci: change web demo to drag_n_drop

CHANGELOG.md, examples/drag_n_drop/src/main.rs, examples/headless/src/main.rs, examples/lottie/src/main.rs, examples/render_layers/src/main.rs, examples/scene/src/main.rs, examples/scene_ui/src/main.rs, examples/svg/src/main.rs, examples/text/src/main.rs, src/integrations/lottie/asset.rs, src/integrations/lottie/mod.rs, src/integrations/svg/asset.rs, src/lib.rs, src/text/vello_text.rs
=> feat: implement required components

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md
Will accompany a release, v0.7.0.
(Draft state unilt #123 merges)
=> chore: release version 0.7.0

examples/headless/Cargo.toml
fix: examples/headless: added missing png feature for bevy dependency to Cargo.toml.
=> fix: examples/headless - added missing 'png' feature 

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md
This will be the last release on bevy 0.15
=> chore: release v0.8.0

CHANGELOG.md, src/integrations/lottie/render.rs, src/integrations/svg/render.rs, src/integrations/text/render.rs, src/render/extract.rs, src/render/systems.rs
Should close: https://github.com/linebender/bevy_vello/issues/164
Resolves the issue where world and screen render items are mixed together, now world is rendered first and screen is rendered ontop.
=> Segregate world and screen space when sorting render items

CHANGELOG.md, src/integrations/text/plugin.rs, src/integrations/text/vello_text.rs
Found a few issues in the calculate text section size systems that this fixes.
1. Because the systems ran in the `Update` schedule, sometimes when changing or adding a `Handle<VelloFont>` to a `VelloTextStyle`, the font would be assigned after calculating the content size.
2. The calculate content size systems previously panicked if the font was missing, now we gracefully `warn!` instead
3. ~~We did not care about world scale scaling for text sections, I've added the system and updated the text section queries to select text sections for the correct space.~~ removed after some reflection, makes no sense to have it in the plugin
=> Calculate text section content size improvements and fixes
